org.gradle.jvmargs=-Xmx6G -XX:+UseParallelGC
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configuration-cache=false

# Minecraft / Fabric
minecraft_version=1.21.11
parchment_minecraft=1.21.11
parchment_version=2025.12.20
fabric_loader_version=0.19.5
fabric_version=0.141.6+1.21.11
loom_version=1.16-SNAPSHOT
java_version=21

# Dependencies
create_fly_version=1.21.11-6.0.9-5
forgeconfigapiport_version=21.11.1

loom.ignoreDependencyLoomVersionValidation=true

systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7890
systemProp.http.nonProxyHosts=localhost|127.*|[::1]
