package com.tterrag.registrate.providers;

import com.tterrag.registrate.providers.modelgen.ModelFile;
import com.tterrag.registrate.providers.modelgen.MultiPartBlockStateBuilder;
import net.minecraft.resources.Identifier;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockState;

import java.util.function.Function;

/**
 * Replaces the registrate shim's empty provider. Methods are no-ops so registration
 * source type-checks; blockstate JSON is not generated by this class.
 */
public class RegistrateBlockstateProvider {
    public void simpleBlock(final Block block) {}

    public void simpleBlock(final Block block, final ModelFile model) {}

    public Identifier modLoc(final String path) {
        return Identifier.fromNamespaceAndPath("simulated", path);
    }

    public Models models() {
        return new Models();
    }

    public MultiPartBlockStateBuilder getMultipartBuilder(final Block block) {
        return new MultiPartBlockStateBuilder();
    }

    public void directionalBlock(final Block block, final Function<BlockState, ModelFile> model) {}

    public void horizontalBlock(final Block block, final Function<BlockState, ModelFile> model) {}

    public void horizontalFaceBlock(final Block block, final Function<BlockState, ModelFile> model) {}

    public static final class Models {
        public ModelFile getExistingFile(final Identifier id) {
            return new ModelFile();
        }

        public ModelBuilder withExistingParent(final String name, final Identifier parent) {
            return new ModelBuilder();
        }
    }

    public static final class ModelBuilder extends ModelFile {
        public ModelBuilder texture(final String key, final Identifier texture) {
            return this;
        }
    }
}
