modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
issueTrackerURL = "${issues}"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author}"
credits = "${credits}"
description = '''${description}'''
logoFile = "icon.png"
logoBlur = false

["lithium:options"]
"mixin.entity.collisions.unpushable_cramming" = false
"mixin.world.chunk_access" = false
"mixin.world.chunk_ticking" = false
"mixin.world.tick_scheduler" = false

[[mixins]]
config = "sable.mixins.json"

[[mixins]]
config = "sable-neoforge.mixins.json"

[[dependencies.sable]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sable]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.sable]]
modId = "flywheel"
type = "optional"
versionRange = "[1.0.6,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.sable]]
modId = "create"
type = "optional"
versionRange = "${create_version_range}"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.sable]]
modId = "sablecompanion"
type = "incompatible"
versionRange = "(${sable_companion_version},)"
reason = "Sable is out of date"

[[dependencies.sable]]
modId = "sodium"
type = "incompatible"
versionRange = "(,${sodium_version})"
reason = "${mod_name} supports Sodium ${sodium_version} and above"

[[dependencies.sable]]
modId = "scalablelux"
type = "incompatible"
