preserve_hierarchy: true

files:
  - source: /simulated/common/src/generated/resources/assets/simulated/lang/en_us.json
    translation: /simulated/common/src/main/resources/assets/simulated/lang/%locale_with_underscore%.json
  - source: /aeronautics/common/src/generated/resources/assets/aeronautics/lang/en_us.json
    translation: /aeronautics/common/src/main/resources/assets/aeronautics/lang/%locale_with_underscore%.json
  - source: /offroad/common/src/generated/resources/assets/offroad/lang/en_us.json
    translation: /offroad/common/src/main/resources/assets/offroad/lang/%locale_with_underscore%.json