# Shared Project Settings
java_version=21

# Mod
mod_version=1.3.2
license=Read attached LICENSE.md

# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

# Parchment Mappings
# https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_minecraft=1.21
parchment_version=2024.11.10

# Fabric
## https://fabricmc.net/develop
fabric_version=0.103.0+1.21.1
fabric_loader_version=0.16.9

# Neoform
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430

# NeoForge
## https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.1.247
neoforge_loader_version_range=[4,)

# Dependencies
veil_version=4.3.2
sable_version=2.0.4-37
sable_companion_version=1.6.0

create_version=6.0.10-280
ponder_version=1.0.81
flywheel_version=1.0.6
registrate_version=MC1.21-1.3.0+67

# only change when mods.toml/fabric.mod.json should be updated
create_mod_version = 6.0.10
sable_mod_version_range = [2.0.0,3.0.0)
flywheel_mod_version = 1.0.6
jei_version = 19.44.0.406
jei_min_version = 19.21.0.247

# Mod Integration
computercraft_tweaked_version = 1.115.1
natures_compass_version = 3.4.0
explorers_compass_version = 3.4.0
curios_version=9.2.2
sodium_version=mc1.21.1-0.6.13-neoforge
iris_version=1.8.12+1.21.1-neoforge

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
