version = '2.0.5+mc1.21.11'
group = 'dev.ryanhcode.sable'

base {
    archivesName = 'sable-sable_rapier-1.21.11'
}

dependencies {
    // The rapier bindings reference Sable's physics API
    compileOnly project(path: ':sable', configuration: 'namedElements')
    compileOnly project(path: ':sable-companion', configuration: 'namedElements')
    modCompileOnly "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_version}"
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand 'version': project.version
    }
}
